// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsViNjgPJyMZ5C64nN7CSggy65CaZFq8A',
    appId: '1:167700736671:web:673db620ad99e9802390aa',
    messagingSenderId: '167700736671',
    projectId: 'straycare-dev',
    authDomain: 'straycare-dev.firebaseapp.com',
    storageBucket: 'straycare-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsd-e1ZVtycyafIsde5rxB5PMMkCv0Cck',
    appId: '1:167700736671:android:f1b0eac50a29ba442390aa',
    messagingSenderId: '167700736671',
    projectId: 'straycare-dev',
    storageBucket: 'straycare-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg2l0Af-MNeUZlr51KnZzCelC2kGM44Y8',
    appId: '1:167700736671:ios:696141d2faaf96b62390aa',
    messagingSenderId: '167700736671',
    projectId: 'straycare-dev',
    storageBucket: 'straycare-dev.firebasestorage.app',
    androidClientId: '167700736671-tfiu1fi0uv5d5e0ojri7r1njvp9h57qd.apps.googleusercontent.com',
    iosClientId: '167700736671-acmkqkpodln7lhibiv8o72pac949vbqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.straycareDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg2l0Af-MNeUZlr51KnZzCelC2kGM44Y8',
    appId: '1:167700736671:ios:696141d2faaf96b62390aa',
    messagingSenderId: '167700736671',
    projectId: 'straycare-dev',
    storageBucket: 'straycare-dev.firebasestorage.app',
    androidClientId: '167700736671-tfiu1fi0uv5d5e0ojri7r1njvp9h57qd.apps.googleusercontent.com',
    iosClientId: '167700736671-acmkqkpodln7lhibiv8o72pac949vbqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.straycareDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsViNjgPJyMZ5C64nN7CSggy65CaZFq8A',
    appId: '1:167700736671:web:ce106a242b64a9dd2390aa',
    messagingSenderId: '167700736671',
    projectId: 'straycare-dev',
    authDomain: 'straycare-dev.firebaseapp.com',
    storageBucket: 'straycare-dev.firebasestorage.app',
  );
}
